"""Grade SERA's final answers (the author, 2026-09-26: "tell it if it's wrong or right, how much, where", graded by A;
dev worlds only, where the caretaker knows the true law). Reads saved units (JSON with world, truth, claim, sure,
right, contradicted, checker_ok, scope, throws, cpu - as the T-S runner writes them) and writes one grade file per
world plus a generated report card. Grades are for learning and for people; they never enter a proof.

  python scripts/sera_grades.py --out <folder holding one sub-folder of units per arm>

Verdicts, in order of merit (the credit ladder's rungs, seen from the answer):
  proven right       sure, the claim is the true law, and the checker re-derived the certificate
  proven, part       sure of a law the truth contains (every term true), but not the whole truth
  right, unsure      the best guess was the true law, but it was not proven (the "flaw in understanding")
  unsure, wrong      not sure, and the best guess was not the true law
  SURE AND WRONG     sure of a law the truth does not contain (must never happen)
  checker refused    sure, but the independent checker refused the certificate
Parts: which of the claim's terms are in the true law (right), which true terms it lacks (missing), which it added
(extra); part score = |right| / |truth or claim terms| (1 only for the exact law). Where: the scope the certificate
states (the x and v box its throws visited)."""
import argparse
import json
from collections import Counter
from pathlib import Path

ORDER = ('proven right', 'proven, part', 'right, unsure', 'unsure, wrong', 'SURE AND WRONG', 'checker refused')
NOTHING = 'nothing but my hand'


def terms(name):
    return set() if name == NOTHING else set(name.split(' + '))


def grade_unit(u):
    truth, claim = terms(u['truth']), terms(u['claim'])
    if u['sure'] and u.get('checker_ok') is False:
        verdict = 'checker refused'
    elif u['sure'] and u['contradicted']:
        verdict = 'SURE AND WRONG'
    elif u['sure']:
        verdict = 'proven right' if u['right'] else 'proven, part'
    else:
        verdict = 'right, unsure' if u['right'] else 'unsure, wrong'
    both = truth | claim
    return dict(world=u['world'], verdict=verdict, truth=u['truth'], answer=u['claim'], sure=bool(u['sure']),
                right_terms=sorted(claim & truth), missing_terms=sorted(truth - claim), extra_terms=sorted(claim - truth),
                part_score=round(len(claim & truth) / len(both), 3) if both else 1.0,
                where=u.get('scope'), throws=u.get('throws'), cpu_s=round(u.get('cpu', 0.0)))


def grade_folder(out):
    out = Path(out)
    card = ['# Report card (generated by scripts/sera_grades.py from the saved units)', '']
    for arm in sorted(p for p in out.iterdir() if p.is_dir() and p.name != 'grades'):
        units = [json.loads(p.read_text()) for p in sorted(arm.glob('*.json'))]
        units = [u for u in units if {'world', 'truth', 'claim', 'sure'} <= set(u)]
        if not units:
            continue
        gdir = out / 'grades' / arm.name
        gdir.mkdir(parents=True, exist_ok=True)
        grades = [grade_unit(u) for u in units]
        for g in grades:
            (gdir / f'{g["world"]}.json').write_text(json.dumps(g, indent=1))
        n = Counter(g['verdict'] for g in grades)
        card += [f'## {arm.name}: {len(grades)} worlds graded', '', '| verdict | worlds |', '|---|---|']
        card += [f'| {v} | {n.get(v, 0)} |' for v in ORDER]
        card += ['', f'Mean part score {sum(g["part_score"] for g in grades) / len(grades):.3f}; '
                     f'median throws {sorted(g["throws"] or 0 for g in grades)[len(grades) // 2]}.', '']
        worst = [g for g in grades if g['verdict'] in ('SURE AND WRONG', 'checker refused', 'right, unsure')]
        for g in worst:
            card.append(f'- {g["world"]}: {g["verdict"]}; truth {g["truth"]}; answer {g["answer"]}; '
                        f'missing {g["missing_terms"]}; extra {g["extra_terms"]}')
        card.append('')
    (out / 'grades').mkdir(parents=True, exist_ok=True)
    (out / 'grades' / 'CARD.md').write_text('\n'.join(card), encoding='utf-8')
    return '\n'.join(card)


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', required=True)
    print(grade_folder(ap.parse_args().out))
